version: '3'

services:
  app:
    build:
      context: app
    container_name: app
    environment:
      - MYSQL_URL=db
      - MYSQL_USERNAME=root
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network
    volumes:
      - ./app:/home/node/app
    tty: true
    ports:
      - "3000:3000"
    entrypoint: wait-for db:3306 -t 40 -- ./start.sh
    depends_on:
      - db

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network
  nginx:
    restart: always
    image: nginx:latest
    container_name: nginx
    volumes:
      - "./nginx/default.conf:/etc/nginx/conf.d/default.conf"    
    ports:
        - "8080:80"
    depends_on:
      - app

networks:
  node-network:
    driver: bridge